<a href="https://colab.research.google.com/github/Rusmandel/Izatov-Rustam/blob/master/Intro_to_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
size = 11
arr = np.zeros((size,size))
print(arr)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [0]:
for i in range(size):
	for j in range(size):
		if (j==i):
			arr[i][j] = 1
		elif (j==((size-1)-i)):
			arr[i][j] = 1
print(arr)

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [3]:
import cv2
horizontal_gradient1 = np.zeros((255,255))
w = horizontal_gradient1.shape[1]
h = horizontal_gradient1.shape[0]

for i in range(h):
    for j in range(w):
        horizontal_gradient1[i][j] = i
horizontal_gradient1

array([[  0.,   0.,   0., ...,   0.,   0.,   0.],
       [  1.,   1.,   1., ...,   1.,   1.,   1.],
       [  2.,   2.,   2., ...,   2.,   2.,   2.],
       ...,
       [252., 252., 252., ..., 252., 252., 252.],
       [253., 253., 253., ..., 253., 253., 253.],
       [254., 254., 254., ..., 254., 254., 254.]])

In [4]:
cv2.imwrite('horizontal_grad1.jpg', horizontal_gradient1)

True

In [5]:
horizontal_gradient2 = horizontal_gradient1 = np.zeros((255,255))

w = horizontal_gradient2.shape[1]
h = horizontal_gradient2.shape[0]
for i in range(h):
    for j in range(w):
        horizontal_gradient2[i][j] = h-i
        
cv2.imwrite('horizontal_grad2.jpg', horizontal_gradient2)

True

In [6]:
vertical_gradient1 = np.zeros((255,255))
w = vertical_gradient1.shape[1]
h = vertical_gradient1.shape[0]
for i in range(h):
    for j in range(w):
        vertical_gradient1[i][j] = j
cv2.imwrite('vertical_grad1.jpg', vertical_gradient1)

True

In [7]:
vertical_gradient2 = np.zeros((255,255))

w = vertical_gradient2.shape[1]
h = vertical_gradient2.shape[0]

for i in range(h):
    for j in range(w):
        vertical_gradient2[i][j] = w-j
        
cv2.imwrite('vertical_grad2.jpg', vertical_gradient2)

True